# -*- coding: utf-8 -*-
"""Coding Assignment-3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MPF17UDQDZjXINTMwiDUZC2nW3EKNFa0

# **Intersection Of Sorted Arrays**
"""

def intersect(A, B):
    result = []
    i, j = 0, 0

    while i < len(A) and j < len(B):
        if A[i] < B[j]:
            i += 1
        elif A[i] > B[j]:
            j += 1
        else:
            result.append(A[i])
            i += 1
            j += 1

    return result

a=int(input('enter number of elements in first set '))
b=int(input('enter number of elements in second set '))
p=[]
q=[]
for i in range(a):
  d=int(input("Enter the number for 1st "))
  p.append(d)
for i in range(b):
  f=int(input("enter the number for 2nd "))
  q.append(f)

output_result = intersect(p, q)
print(output_result)

"""# **Verify Prime**"""

num=int(input('enter number '))
if num > 1:
    for i in range(2, num):
        if (num % i) == 0:
            print("False")
            break
    else:
        print("True")
else:
    print("False")

"""# **Ants on a Triangle**"""

P = 1/2
Psame = P**3
Pnot_same = 1 - Psame

rounded_probability = round(Pnot_same, 2)
print(rounded_probability)

"""# **Excel Column Title**"""

def convertToTitle(A):
    result = ""

    while A > 0:
        A -= 1
        remainder = A % 26

        char = chr(ord('A') + remainder)
        result = char + result
        A //= 26

    return result

k=int(input("enter the number "))
output_result1 = convertToTitle(k)
print(output_result1)

"""# **Reverse integer**"""

k=int(input("Enter the number "))
a=str(k)
if k>0:
  print(a[::-1])
else:
  print('-'+a[:0:-1])

